# -*- coding: utf-8 -*-
"""E8_TextSummary2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1RRj6bxCQlJN30OKo2frBHsQ6OPMrsP

<a href="https://colab.research.google.com/github/sergiomora03/AdvancedTopicsAnalytics/blob/main/exercises/E7-TextSummary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INTEGRANTES:**
- Luis Alejandro Garzón Ramirez
- Zorayda Acevedo Jimenez
- Yulieth Danitza Aguillón Ortega

## Text Summary

Text summarization is important in the field of machine learning and natural language processing for several reasons:

1. **Information Retrieval:** Text summarization helps users quickly grasp the main points or key information from a large document, making it easier to decide whether to read the full document or not. This is particularly valuable in scenarios where individuals are inundated with vast amounts of textual data, such as news articles, research papers, or social media posts.

2. **Time Efficiency:** Summarization algorithms can process and generate summaries much faster than humans can read and summarize large texts. This saves time and allows users to focus their attention on the most relevant content.

3. **Content Extraction:** Text summarization can automatically extract essential information from a document, enabling applications like content recommendation, keyword extraction, and topic modeling.

4. **Content Generation:** Summarization models can be used to generate concise, coherent, and informative summaries for various purposes, such as creating abstracts for research papers, news article headlines, or social media post previews.

5. **Multilingual Support:** Text summarization can be applied to texts in multiple languages, making it a valuable tool for global communication and information retrieval.

6. **Personalization:** Summarization can be personalized to individual preferences. Machine learning models can learn from user feedback to generate summaries that align more closely with a user's interests and priorities.

7. **Scalability:** As the volume of digital content continues to grow, automated summarization becomes crucial for scaling information processing and retrieval. Machine learning-based summarization models can adapt and handle large volumes of text efficiently.

8. **Legal and Compliance:** In legal and regulatory contexts, automated summarization can help organizations review contracts, policies, and legal documents to ensure compliance and identify critical clauses or information.

9. **Search Engine Optimization (SEO):** Summarized content can be used to create concise and engaging snippets for search engine results, improving the discoverability of web content.

10. **Content Creation:** Summarization can be integrated into content creation tools, helping authors and content creators generate concise and informative content more efficiently.

Overall, text summarization is an essential component of machine learning and natural language processing, enabling efficient information retrieval, content extraction, and content generation across a wide range of applications and industries. It plays a critical role in handling the ever-increasing amount of textual data available in the digital age.

---
Exercise:

Now, as a data scientist expert in NLP, you are asked to create a model to be able to summarize text in Spanish. Your stakeholders will pass you an article and your model should summarize it.
"""

!pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

# URL del artículo
url = "https://time.com/collection/time100-ai/6309026/geoffrey-hinton/"

# Realizar una solicitud HTTP para obtener el contenido de la página
response = requests.get(url)

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    # Analizar el contenido HTML de la página con BeautifulSoup
    soup = BeautifulSoup(response.text, "html.parser")

    # Encontrar el contenido del artículo (puedes inspeccionar el HTML de la página para encontrar la estructura adecuada)
    article_content = soup.find("div", {"class": "article-content"})

    # Extraer el texto del artículo
    article_text = ""
    for paragraph in article_content.find_all("p"):
        article_text += paragraph.get_text() + "\n"

    # Imprimir el texto del artículo
    print(article_text)
else:
    print("Error al obtener la página:", response.status_code)

!pip install langdetect

"""Codigo para extraer el articulo, determinar el idioma, dividir el texto en fragmentos manejables, realizar el resumen con BART y finalmente mostrar el resumen en español (traduccion usando Helinski)"""

import requests
from bs4 import BeautifulSoup
from transformers import pipeline
from langdetect import detect

# Función para obtener el texto del artículo desde una URL
def obtener_texto(url):
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        article_content = soup.find("div", {"class": "article-content"})

        if article_content:
            texto = "\n".join([p.get_text() for p in article_content.find_all("p")])
            return texto.strip()

    print("Error al obtener la página:", response.status_code)
    return None

# Función para detectar el idioma
def detectar_idioma(texto):
    return detect(texto)

# Función para dividir el texto en fragmentos manejables
def dividir_texto(texto, max_input_length=1024):
    return [texto[i:i + max_input_length] for i in range(0, len(texto), max_input_length)]

# Función para resumir fragmentos de texto usando BART
def resumir_texto(fragmentos, max_length=80, min_length=20):
    resumen_pipeline = pipeline("summarization", model="facebook/bart-large-cnn")
    resúmenes = []

    for parte in fragmentos:
        try:
            resumen = resumen_pipeline(parte, max_length=max_length, min_length=min_length, do_sample=False)
            resúmenes.append(resumen[0]['summary_text'])
        except Exception as e:
            print(f"Error al resumir fragmento: {e}")

    return " ".join(resúmenes)

# Función para traducir texto al español si es necesario
def traducir_al_español(texto):
    traduccion_pipeline = pipeline("translation", model="Helsinki-NLP/opus-mt-en-es")
    return traduccion_pipeline(texto)[0]['translation_text']

# Función principal que une todo el proceso
def procesar_articulo(url):
    texto = obtener_texto(url)
    if not texto or len(texto) < 50:
        print("El artículo es demasiado corto o no se encontró contenido.")
        return

    idioma = detectar_idioma(texto)
    print(f"Idioma detectado: {idioma}")

    fragmentos = dividir_texto(texto)

    resumen = resumir_texto(fragmentos)

    if idioma == "en":
        resumen = traducir_al_español(resumen)

    print("\nResumen en español:\n", resumen)

"""Codigo en uso"""

url = "https://time.com/collection/time100-ai/6309026/geoffrey-hinton/"
procesar_articulo(url)